table medidas
	lineageTag: f7632a55-01ca-4e5f-88f6-3e1d77124588

	measure 'Receita Total' = ```
			
			VAR Receita =
			    CALCULATE (
			        SUM ( fat_lancamentos_financeiros[valor] ),
			        KEEPFILTERS ( fat_lancamentos_financeiros[tipo] = "RECEITA" )
			    )
			RETURN
			    COALESCE ( Receita, 0 )
			
			```
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 01 Base
		lineageTag: db8ebaf4-b1de-448c-9d10-a49dc074e7f1

	measure 'Despesa Total' = ```
			
			VAR Despesa =
			    CALCULATE (
			        SUM ( fat_lancamentos_financeiros[valor] ),
			        KEEPFILTERS ( fat_lancamentos_financeiros[tipo] = "DESPESA" )
			    )
			RETURN
			    COALESCE ( Despesa, 0 )
			
			```
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 01 Base
		lineageTag: 7ecb3610-a39a-4093-931d-ab49894006e5

	measure Resultado = [Receita Total] - [Despesa Total]
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 01 Base
		lineageTag: c0cfd5d2-3d7e-4c89-b986-ba1e5fbfec46

	measure 'Margem de Resultado %' = DIVIDE ( [Resultado], [Receita Total] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 01 Base
		lineageTag: 77b6dc56-73f6-4669-bde4-44a7950dff2e

	measure '% Receita por Categoria' = ```
			
			DIVIDE (
			    [Receita Total],
			    CALCULATE ( [Receita Total], REMOVEFILTERS ( dim_categoria ) )
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 03 Participacao
		lineageTag: 340abe5d-b83d-4cc0-82de-dd968547142d

	measure 'Receita Mes Anterior' = ```
			
			CALCULATE (
			    [Receita Total],
			    DATEADD ( dim_calendario[Data], -1, MONTH )
			)
			
			```
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 02 Temporal
		lineageTag: 070db358-1830-4318-92e0-4d849a9d986a

	measure 'Despesa Mes Anterior' = ```
			
			CALCULATE (
			    [Despesa Total],
			    DATEADD ( dim_calendario[Data], -1, MONTH )
			)
			
			```
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 02 Temporal
		lineageTag: f1f2539f-24f8-45bb-83bb-dbd0dafd90fc

	measure 'Resultado Mes Anterior' = [Receita Mes Anterior] - [Despesa Mes Anterior]
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 02 Temporal
		lineageTag: 6f6bee33-2796-4395-a41e-b4629f4f9707

	measure Saldo = [Resultado]
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 01 Base
		lineageTag: 08c11ac7-611d-4e1a-9b53-f0d7bda41c11

	measure 'Total de Lancamentos' = COUNTROWS ( fat_lancamentos_financeiros )
		formatString: #,##0
		displayFolder: 01 Base
		lineageTag: d9f2e3c0-5f9f-46bc-8c80-3f3f9ad9d001

	measure 'Lancamentos de Receita' = ```
			
			CALCULATE (
			    [Total de Lancamentos],
			    KEEPFILTERS ( fat_lancamentos_financeiros[tipo] = "RECEITA" )
			)
			
			```
		formatString: #,##0
		isHidden
		displayFolder: 00 Auxiliares
		lineageTag: 7f92c12e-9ca2-4d1e-bf86-093d7d2d9e02

	measure 'Lancamentos de Despesa' = ```
			
			CALCULATE (
			    [Total de Lancamentos],
			    KEEPFILTERS ( fat_lancamentos_financeiros[tipo] = "DESPESA" )
			)
			
			```
		formatString: #,##0
		isHidden
		displayFolder: 00 Auxiliares
		lineageTag: c3494224-b60f-4d7b-96f0-5ba22ee0977d

	measure 'Ticket Medio' = DIVIDE ( [Receita Total], [Lancamentos de Receita] )
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 01 Base
		lineageTag: 07716641-3148-4586-a577-9868de130e0b

	measure 'Valor Medio por Lancamento' = DIVIDE ( [Receita Total] + [Despesa Total], [Total de Lancamentos] )
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 01 Base
		lineageTag: 988fbadb-1be3-440c-89ed-4f6e487e9b9f

	measure 'Variacao Receita vs Mes Anterior' = [Receita Total] - [Receita Mes Anterior]
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 02 Temporal
		lineageTag: a1925e67-75a5-4f36-a034-1d8b5838246b

	measure 'Variacao Receita % vs Mes Anterior' = DIVIDE ( [Variacao Receita vs Mes Anterior], [Receita Mes Anterior] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 02 Temporal
		lineageTag: 40b068ab-fbd5-4a34-a1ea-4ce4c4d06665

	measure 'Variacao Despesa vs Mes Anterior' = [Despesa Total] - [Despesa Mes Anterior]
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 02 Temporal
		lineageTag: 7ed00aec-a0e0-46d5-8355-f2a4130b3f61

	measure 'Variacao Despesa % vs Mes Anterior' = DIVIDE ( [Variacao Despesa vs Mes Anterior], [Despesa Mes Anterior] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 02 Temporal
		lineageTag: 61fbbd87-5c41-485d-b643-d4be6e76c661

	measure 'Variacao Resultado vs Mes Anterior' = [Resultado] - [Resultado Mes Anterior]
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 02 Temporal
		lineageTag: 8ac717d3-0b0f-44db-b165-59a47759c4ab

	measure 'Variacao Resultado % vs Mes Anterior' = DIVIDE ( [Variacao Resultado vs Mes Anterior], [Resultado Mes Anterior] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 02 Temporal
		lineageTag: e99f2e4f-343b-484d-8702-7e7441a6f03b

	measure 'Receita Acumulada' = ```
			
			VAR DataAtual = MAX ( dim_calendario[Data] )
			RETURN
			    CALCULATE (
			        [Receita Total],
			        FILTER (
			            ALLSELECTED ( dim_calendario[Data] ),
			            dim_calendario[Data] <= DataAtual
			        )
			    )
			
			```
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 02 Temporal
		lineageTag: 4b43b02b-1748-4f87-b1de-a5a9b15c6ac3

	measure 'Despesa Acumulada' = ```
			
			VAR DataAtual = MAX ( dim_calendario[Data] )
			RETURN
			    CALCULATE (
			        [Despesa Total],
			        FILTER (
			            ALLSELECTED ( dim_calendario[Data] ),
			            dim_calendario[Data] <= DataAtual
			        )
			    )
			
			```
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 02 Temporal
		lineageTag: f862d106-87f7-4352-8e75-010d9fa1829f

	measure 'Resultado Acumulado' = [Receita Acumulada] - [Despesa Acumulada]
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 02 Temporal
		lineageTag: c89d0f97-2600-4f1d-b12c-cb18d93a7d97

	measure 'Receita YTD' = ```
			
			TOTALYTD (
			    [Receita Total],
			    dim_calendario[Data]
			)
			
			```
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 02 Temporal
		lineageTag: d12e42f8-4e35-4d8d-8c38-e434ff256a2c

	measure 'Despesa YTD' = ```
			
			TOTALYTD (
			    [Despesa Total],
			    dim_calendario[Data]
			)
			
			```
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 02 Temporal
		lineageTag: 8fd7c447-3202-4fdb-b94b-02c782fd20b2

	measure 'Resultado YTD' = [Receita YTD] - [Despesa YTD]
		formatString: R$ #,##0.00;-R$ #,##0.00;R$ #,##0.00
		displayFolder: 02 Temporal
		lineageTag: 95fd63e0-bdf4-413d-94ee-b8e1b61ea238

	measure '% Despesa por Categoria' = ```
			
			DIVIDE (
			    [Despesa Total],
			    CALCULATE ( [Despesa Total], REMOVEFILTERS ( dim_categoria ) )
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 03 Participacao
		lineageTag: 601a1b59-4054-4023-8136-44c8ded9f9d0

	measure '% Receita por Forma de Pagamento' = ```
			
			DIVIDE (
			    [Receita Total],
			    CALCULATE ( [Receita Total], REMOVEFILTERS ( dim_forma_pagamento ) )
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 03 Participacao
		lineageTag: 6f7431b6-1fd2-45bd-b6cf-1c9560061f63

	measure '% Despesa por Forma de Pagamento' = ```
			
			DIVIDE (
			    [Despesa Total],
			    CALCULATE ( [Despesa Total], REMOVEFILTERS ( dim_forma_pagamento ) )
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 03 Participacao
		lineageTag: f19cb6d4-55e6-478c-a56c-70b753ca6c08

	measure 'Indicador Resultado Positivo/Negativo' = ```
			
			IF (
			    [Resultado] >= 0,
			    "Positivo",
			    "Negativo"
			)
			
			```
		displayFolder: 04 Indicadores
		lineageTag: 5d318810-8781-41fb-afba-a213a89b5a47

	measure 'Cor Resultado' = IF ( [Resultado] >= 0, "#22C55E", "#EF4444" )
		displayFolder: 04 Indicadores
		lineageTag: 5e16958b-2d9a-4c82-8fa9-59fb8c1024ba

	measure 'Cor Variacao Receita' = IF ( [Variacao Receita vs Mes Anterior] >= 0, "#22C55E", "#EF4444" )
		displayFolder: 04 Indicadores
		lineageTag: 1fe11dc7-bd40-4e88-a147-4ff7320c04ca

	measure 'Cor Variacao Despesa' = IF ( [Variacao Despesa vs Mes Anterior] <= 0, "#22C55E", "#EF4444" )
		displayFolder: 04 Indicadores
		lineageTag: 5470ee7d-58d9-4bd1-93d2-7a0259bca1dc

	measure 'Cor Variacao Resultado' = IF ( [Variacao Resultado vs Mes Anterior] >= 0, "#22C55E", "#EF4444" )
		displayFolder: 04 Indicadores
		lineageTag: c924b0d9-5320-4c0c-9365-f2247f2f8719

	measure 'Texto Variacao Receita' = ```
			
			VAR Variacao = [Variacao Receita % vs Mes Anterior]
			RETURN
			    IF (
			        ISBLANK ( Variacao ),
			        "Sem base comparativa",
			        FORMAT ( Variacao, "+0.0%;-0.0%;0.0%" ) & " vs mes anterior"
			    )
			
			```
		displayFolder: 04 Indicadores
		lineageTag: 95543dbd-8dcb-4512-807f-1ffec32dc3a3

	measure 'Texto Variacao Despesa' = ```
			
			VAR Variacao = [Variacao Despesa % vs Mes Anterior]
			RETURN
			    IF (
			        ISBLANK ( Variacao ),
			        "Sem base comparativa",
			        FORMAT ( Variacao, "+0.0%;-0.0%;0.0%" ) & " vs mes anterior"
			    )
			
			```
		displayFolder: 04 Indicadores
		lineageTag: 35182528-35f4-4c7f-b024-62b952e487c8

	measure 'Texto Variacao Resultado' = ```
			
			VAR Variacao = [Variacao Resultado % vs Mes Anterior]
			RETURN
			    IF (
			        ISBLANK ( Variacao ),
			        "Sem base comparativa",
			        FORMAT ( Variacao, "+0.0%;-0.0%;0.0%" ) & " vs mes anterior"
			    )
			
			```
		displayFolder: 04 Indicadores
		lineageTag: d9a2b610-f159-4d33-8026-c154edec9344

	measure 'Periodo Selecionado Texto' =
			VAR DataMin = MIN ( dim_calendario[Data] )
			VAR DataMax = MAX ( dim_calendario[Data] )
			RETURN
			    IF (
			        ISBLANK ( DataMin ) || ISBLANK ( DataMax ),
			        "Periodo nao filtrado",
			        FORMAT ( DataMin, "dd/mm/yyyy" ) & " - " & FORMAT ( DataMax, "dd/mm/yyyy" )
			    )
		isHidden
		displayFolder: 05 HTML
		lineageTag: 0b425f16-cedc-4ff6-8a60-f2a0f50c1f18

	measure 'HTML Header Visao' =
			"<div style='box-sizing:border-box;height:100%;padding:18px 22px;border-radius:18px;background:linear-gradient(135deg,#101B2E 0%,#0B1324 62%,#08111F 100%);border:1px solid rgba(148,163,184,.16);box-shadow:0 18px 38px rgba(0,0,0,.28);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC;overflow:hidden;position:relative'>"
			& "<div style='position:absolute;right:-70px;top:-95px;width:220px;height:220px;border-radius:999px;background:radial-gradient(circle,rgba(56,189,248,.22),rgba(56,189,248,0) 66%)'></div>"
			& "<div style='font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:#38BDF8;font-weight:700'>Finance Executive Suite</div>"
			& "<div style='margin-top:7px;font-size:26px;line-height:31px;font-weight:700'>Visao Executiva</div>"
			& "<div style='margin-top:4px;font-size:12px;color:#94A3B8'>Saude financeira consolidada | " & [Periodo Selecionado Texto] & "</div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: c3f5d441-366b-452e-92a1-3aa3dd498830

	measure 'HTML Header Receitas' =
			"<div style='box-sizing:border-box;height:100%;padding:18px 22px;border-radius:18px;background:linear-gradient(135deg,#10241F 0%,#0B1826 60%,#07111F 100%);border:1px solid rgba(52,211,153,.18);box-shadow:0 18px 38px rgba(0,0,0,.28);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC;overflow:hidden;position:relative'>"
			& "<div style='position:absolute;right:-70px;top:-95px;width:220px;height:220px;border-radius:999px;background:radial-gradient(circle,rgba(52,211,153,.22),rgba(52,211,153,0) 66%)'></div>"
			& "<div style='font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:#34D399;font-weight:700'>Revenue Intelligence</div>"
			& "<div style='margin-top:7px;font-size:26px;line-height:31px;font-weight:700'>Receitas</div>"
			& "<div style='margin-top:4px;font-size:12px;color:#94A3B8'>Entradas, recorrencia e canais de pagamento | " & [Periodo Selecionado Texto] & "</div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: f66c657e-f056-423c-ace3-105e808aa8b4

	measure 'HTML Header Despesas' =
			"<div style='box-sizing:border-box;height:100%;padding:18px 22px;border-radius:18px;background:linear-gradient(135deg,#2A1218 0%,#151827 62%,#07111F 100%);border:1px solid rgba(248,113,113,.18);box-shadow:0 18px 38px rgba(0,0,0,.28);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC;overflow:hidden;position:relative'>"
			& "<div style='position:absolute;right:-70px;top:-95px;width:220px;height:220px;border-radius:999px;background:radial-gradient(circle,rgba(248,113,113,.21),rgba(248,113,113,0) 66%)'></div>"
			& "<div style='font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:#F87171;font-weight:700'>Cost Control</div>"
			& "<div style='margin-top:7px;font-size:26px;line-height:31px;font-weight:700'>Despesas</div>"
			& "<div style='margin-top:4px;font-size:12px;color:#94A3B8'>Gastos, concentracao e maiores impactos | " & [Periodo Selecionado Texto] & "</div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: 8fd69102-2a15-4ff4-a5a2-b25fc1157593

	measure 'HTML Header Resultado' =
			"<div style='box-sizing:border-box;height:100%;padding:18px 22px;border-radius:18px;background:linear-gradient(135deg,#231B10 0%,#101827 58%,#07111F 100%);border:1px solid rgba(245,158,11,.18);box-shadow:0 18px 38px rgba(0,0,0,.28);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC;overflow:hidden;position:relative'>"
			& "<div style='position:absolute;right:-70px;top:-95px;width:220px;height:220px;border-radius:999px;background:radial-gradient(circle,rgba(245,158,11,.22),rgba(245,158,11,0) 66%)'></div>"
			& "<div style='font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:#F59E0B;font-weight:700'>Performance</div>"
			& "<div style='margin-top:7px;font-size:26px;line-height:31px;font-weight:700'>Resultado Financeiro</div>"
			& "<div style='margin-top:4px;font-size:12px;color:#94A3B8'>Lucro, margem e evolucao acumulada | " & [Periodo Selecionado Texto] & "</div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: 11489618-3621-40c4-a690-3a07de73605d

	measure 'HTML Header Detalhamento' =
			"<div style='box-sizing:border-box;height:100%;padding:18px 22px;border-radius:18px;background:linear-gradient(135deg,#101B2E 0%,#101827 62%,#07111F 100%);border:1px solid rgba(148,163,184,.16);box-shadow:0 18px 38px rgba(0,0,0,.28);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC;overflow:hidden;position:relative'>"
			& "<div style='font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:#A78BFA;font-weight:700'>Transaction Explorer</div>"
			& "<div style='margin-top:7px;font-size:26px;line-height:31px;font-weight:700'>Detalhamento</div>"
			& "<div style='margin-top:4px;font-size:12px;color:#94A3B8'>Consulta granular dos lancamentos | " & [Periodo Selecionado Texto] & "</div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: 76b2c87f-3666-4f85-9712-5ed803fb35b2

	measure 'HTML KPI Receita' =
			VAR Valor = [Receita Total]
			VAR Delta = [Variacao Receita % vs Mes Anterior]
			VAR Positivo = Delta >= 0
			VAR Cor = IF ( Positivo, "#34D399", "#F87171" )
			VAR Fundo = IF ( Positivo, "rgba(52,211,153,.14)", "rgba(248,113,113,.14)" )
			VAR Icone = IF ( Positivo, "&#8593;", "&#8595;" )
			VAR DeltaTexto = IF ( ISBLANK ( Delta ), "Sem base", FORMAT ( Delta, "+0.0%;-0.0%;0.0%" ) )
			RETURN
			    "<div style='box-sizing:border-box;height:100%;padding:16px 17px;border-radius:18px;background:linear-gradient(180deg,rgba(17,27,44,.98),rgba(11,18,32,.98));border:1px solid rgba(56,189,248,.18);box-shadow:0 12px 28px rgba(0,0,0,.26);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC'>"
			    & "<div style='display:flex;align-items:center;justify-content:space-between'><span style='font-size:11px;text-transform:uppercase;letter-spacing:.11em;color:#94A3B8;font-weight:700'>Receita</span><span style='width:28px;height:28px;border-radius:10px;background:rgba(56,189,248,.14);color:#38BDF8;text-align:center;line-height:28px;font-weight:800'>R</span></div>"
			    & "<div style='margin-top:14px;font-size:27px;line-height:30px;font-weight:750;color:#F8FAFC'>" & FORMAT ( Valor, "R$ #,##0.00" ) & "</div>"
			    & "<div style='margin-top:12px;display:inline-flex;align-items:center;gap:6px;padding:5px 9px;border-radius:999px;background:" & Fundo & ";color:" & Cor & ";font-size:12px;font-weight:700'>" & Icone & " " & DeltaTexto & "</div>"
			    & "<div style='margin-top:8px;font-size:11px;color:#64748B'>vs mes anterior</div>"
			    & "</div>"
		displayFolder: 05 HTML
		lineageTag: 3f66bb43-a172-4860-9e67-1e92868af56e

	measure 'HTML KPI Despesa' =
			VAR Valor = [Despesa Total]
			VAR Delta = [Variacao Despesa % vs Mes Anterior]
			VAR Favoravel = [Variacao Despesa vs Mes Anterior] <= 0
			VAR Cor = IF ( Favoravel, "#34D399", "#F87171" )
			VAR Fundo = IF ( Favoravel, "rgba(52,211,153,.14)", "rgba(248,113,113,.14)" )
			VAR Icone = IF ( Favoravel, "&#8595;", "&#8593;" )
			VAR DeltaTexto = IF ( ISBLANK ( Delta ), "Sem base", FORMAT ( Delta, "+0.0%;-0.0%;0.0%" ) )
			RETURN
			    "<div style='box-sizing:border-box;height:100%;padding:16px 17px;border-radius:18px;background:linear-gradient(180deg,rgba(17,27,44,.98),rgba(11,18,32,.98));border:1px solid rgba(248,113,113,.18);box-shadow:0 12px 28px rgba(0,0,0,.26);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC'>"
			    & "<div style='display:flex;align-items:center;justify-content:space-between'><span style='font-size:11px;text-transform:uppercase;letter-spacing:.11em;color:#94A3B8;font-weight:700'>Despesa</span><span style='width:28px;height:28px;border-radius:10px;background:rgba(248,113,113,.14);color:#F87171;text-align:center;line-height:28px;font-weight:800'>D</span></div>"
			    & "<div style='margin-top:14px;font-size:27px;line-height:30px;font-weight:750;color:#F8FAFC'>" & FORMAT ( Valor, "R$ #,##0.00" ) & "</div>"
			    & "<div style='margin-top:12px;display:inline-flex;align-items:center;gap:6px;padding:5px 9px;border-radius:999px;background:" & Fundo & ";color:" & Cor & ";font-size:12px;font-weight:700'>" & Icone & " " & DeltaTexto & "</div>"
			    & "<div style='margin-top:8px;font-size:11px;color:#64748B'>controle de gastos</div>"
			    & "</div>"
		displayFolder: 05 HTML
		lineageTag: 71915a8f-8ea9-4b4d-a420-281c9cf184bb

	measure 'HTML KPI Resultado' =
			VAR Valor = [Resultado]
			VAR Delta = [Variacao Resultado % vs Mes Anterior]
			VAR Positivo = Valor >= 0
			VAR Cor = IF ( Positivo, "#34D399", "#F87171" )
			VAR Fundo = IF ( Positivo, "rgba(52,211,153,.14)", "rgba(248,113,113,.14)" )
			VAR Icone = IF ( Positivo, "&#8593;", "&#8595;" )
			VAR DeltaTexto = IF ( ISBLANK ( Delta ), "Sem base", FORMAT ( Delta, "+0.0%;-0.0%;0.0%" ) )
			RETURN
			    "<div style='box-sizing:border-box;height:100%;padding:16px 17px;border-radius:18px;background:linear-gradient(180deg,rgba(17,27,44,.98),rgba(11,18,32,.98));border:1px solid rgba(52,211,153,.20);box-shadow:0 12px 28px rgba(0,0,0,.26);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC'>"
			    & "<div style='display:flex;align-items:center;justify-content:space-between'><span style='font-size:11px;text-transform:uppercase;letter-spacing:.11em;color:#94A3B8;font-weight:700'>Resultado</span><span style='width:28px;height:28px;border-radius:10px;background:" & Fundo & ";color:" & Cor & ";text-align:center;line-height:28px;font-weight:800'>" & Icone & "</span></div>"
			    & "<div style='margin-top:14px;font-size:27px;line-height:30px;font-weight:750;color:" & Cor & "'>" & FORMAT ( Valor, "R$ #,##0.00" ) & "</div>"
			    & "<div style='margin-top:12px;display:inline-flex;align-items:center;gap:6px;padding:5px 9px;border-radius:999px;background:" & Fundo & ";color:" & Cor & ";font-size:12px;font-weight:700'>" & DeltaTexto & "</div>"
			    & "<div style='margin-top:8px;font-size:11px;color:#64748B'>performance liquida</div>"
			    & "</div>"
		displayFolder: 05 HTML
		lineageTag: 265b7891-69db-4950-a036-4a3bfbe1d18a

	measure 'HTML KPI Margem' =
			VAR Valor = [Margem de Resultado %]
			VAR Delta = [Variacao Resultado % vs Mes Anterior]
			VAR Positivo = Valor >= 0
			VAR Cor = IF ( Positivo, "#38BDF8", "#F87171" )
			VAR Fundo = IF ( Positivo, "rgba(56,189,248,.14)", "rgba(248,113,113,.14)" )
			VAR DeltaTexto = IF ( ISBLANK ( Delta ), "Sem base", FORMAT ( Delta, "+0.0%;-0.0%;0.0%" ) )
			RETURN
			    "<div style='box-sizing:border-box;height:100%;padding:16px 17px;border-radius:18px;background:linear-gradient(180deg,rgba(17,27,44,.98),rgba(11,18,32,.98));border:1px solid rgba(56,189,248,.18);box-shadow:0 12px 28px rgba(0,0,0,.26);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC'>"
			    & "<div style='display:flex;align-items:center;justify-content:space-between'><span style='font-size:11px;text-transform:uppercase;letter-spacing:.11em;color:#94A3B8;font-weight:700'>Margem</span><span style='width:28px;height:28px;border-radius:10px;background:rgba(56,189,248,.14);color:#38BDF8;text-align:center;line-height:28px;font-weight:800'>%</span></div>"
			    & "<div style='margin-top:14px;font-size:31px;line-height:30px;font-weight:750;color:" & Cor & "'>" & FORMAT ( Valor, "0.0%" ) & "</div>"
			    & "<div style='margin-top:12px;display:inline-flex;align-items:center;gap:6px;padding:5px 9px;border-radius:999px;background:" & Fundo & ";color:" & Cor & ";font-size:12px;font-weight:700'>" & DeltaTexto & "</div>"
			    & "<div style='margin-top:8px;font-size:11px;color:#64748B'>rentabilidade</div>"
			    & "</div>"
		displayFolder: 05 HTML
		lineageTag: 8b0d601f-fcf8-4f7f-a902-a4422f3e8238

	measure 'HTML KPI Lancamentos' =
			"<div style='box-sizing:border-box;height:100%;padding:16px 17px;border-radius:18px;background:linear-gradient(180deg,rgba(17,27,44,.98),rgba(11,18,32,.98));border:1px solid rgba(167,139,250,.18);box-shadow:0 12px 28px rgba(0,0,0,.26);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC'>"
			& "<div style='display:flex;align-items:center;justify-content:space-between'><span style='font-size:11px;text-transform:uppercase;letter-spacing:.11em;color:#94A3B8;font-weight:700'>Lancamentos</span><span style='width:28px;height:28px;border-radius:10px;background:rgba(167,139,250,.14);color:#A78BFA;text-align:center;line-height:28px;font-weight:800'>#</span></div>"
			& "<div style='margin-top:14px;font-size:31px;line-height:30px;font-weight:750;color:#F8FAFC'>" & FORMAT ( [Total de Lancamentos], "#,##0" ) & "</div>"
			& "<div style='margin-top:12px;display:inline-flex;align-items:center;gap:6px;padding:5px 9px;border-radius:999px;background:rgba(167,139,250,.14);color:#C4B5FD;font-size:12px;font-weight:700'>operacoes</div>"
			& "<div style='margin-top:8px;font-size:11px;color:#64748B'>volume no periodo</div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: 24d6efe2-18d4-4e2a-91fc-1887b1eeed55

	measure 'HTML Filter Panel' =
			"<div style='box-sizing:border-box;height:100%;padding:16px;border-radius:18px;background:linear-gradient(180deg,rgba(15,23,42,.96),rgba(8,15,28,.96));border:1px solid rgba(148,163,184,.14);box-shadow:0 18px 38px rgba(0,0,0,.24);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC'>"
			& "<div style='font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:#38BDF8;font-weight:800'>Filtros</div>"
			& "<div style='margin-top:8px;font-size:18px;font-weight:750'>Refine a analise</div>"
			& "<div style='margin-top:6px;font-size:11px;line-height:16px;color:#94A3B8'>Use os segmentadores para ajustar periodo, categoria, forma de pagamento e tipo.</div>"
			& "<div style='margin-top:18px;padding:10px 12px;border-radius:12px;background:rgba(56,189,248,.10);border:1px solid rgba(56,189,248,.14);font-size:11px;color:#BAE6FD'>Para limpar filtros, use o icone de borracha do proprio segmentador.</div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: aebf8227-aed1-4da4-9f3d-a9f1c7c6989c

	measure 'HTML Insights Visao' =
			
			VAR _Status =
			    IF ( [Resultado] >= 0, "financeiramente saudável", "em ponto de atenção" )
			VAR _Cor =
			    IF ( [Resultado] >= 0, "#34D399", "#F87171" )
			VAR _Badge =
			    IF (
			        [Resultado] >= 0,
			        "Resultado positivo no período selecionado",
			        "Resultado negativo no período selecionado"
			    )
			RETURN
			    "<div style='box-sizing:border-box;height:100%;padding:22px;border-radius:20px;background:linear-gradient(135deg,#0F1B2D 0%,#111F33 100%);border:1px solid rgba(255,255,255,.08);box-shadow:0 18px 45px rgba(0,0,0,.28);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC'>"
			    & "<div style='font-size:12px;letter-spacing:1.6px;text-transform:uppercase;color:#F59E0B;font-weight:800'>Resumo executivo</div>"
			    & "<div style='margin-top:12px;font-size:24px;line-height:30px;font-weight:750'>O período está <span style='color:" & _Cor & "'>" & _Status & "</span>.</div>"
			    & "<div style='margin-top:12px;display:inline-flex;padding:7px 11px;border-radius:999px;background:rgba(56,189,248,.12);color:#BAE6FD;font-size:12px;font-weight:700'>" & _Badge & "</div>"
			    & "<div style='margin-top:22px;display:grid;grid-template-columns:1fr 1fr;gap:12px'>"
			    & "<div style='padding:14px;border-radius:14px;background:rgba(34,197,94,.09);border:1px solid rgba(34,197,94,.12)'><div style='font-size:11px;color:#94A3B8'>Receita</div><div style='margin-top:6px;font-size:16px;font-weight:750'>" & FORMAT ( [Receita Total], "R$ #,##0.00" ) & "</div></div>"
			    & "<div style='padding:14px;border-radius:14px;background:rgba(239,68,68,.09);border:1px solid rgba(239,68,68,.12)'><div style='font-size:11px;color:#94A3B8'>Despesa</div><div style='margin-top:6px;font-size:16px;font-weight:750'>" & FORMAT ( [Despesa Total], "R$ #,##0.00" ) & "</div></div>"
			    & "<div style='padding:14px;border-radius:14px;background:rgba(56,189,248,.09);border:1px solid rgba(56,189,248,.12)'><div style='font-size:11px;color:#94A3B8'>Resultado</div><div style='margin-top:6px;font-size:16px;font-weight:750;color:" & _Cor & "'>" & FORMAT ( [Resultado], "R$ #,##0.00" ) & "</div></div>"
			    & "<div style='padding:14px;border-radius:14px;background:rgba(245,158,11,.09);border:1px solid rgba(245,158,11,.12)'><div style='font-size:11px;color:#94A3B8'>Margem</div><div style='margin-top:6px;font-size:16px;font-weight:750'>" & FORMAT ( [Margem de Resultado %], "0.0%" ) & "</div></div>"
			    & "</div></div>"
		displayFolder: 05 HTML
		lineageTag: 35c212b1-5eda-4fb1-bc7f-4f81738863d2

	measure 'HTML KPI Receita Anterior' =
			"<div style='box-sizing:border-box;height:100%;padding:16px 17px;border-radius:18px;background:linear-gradient(180deg,rgba(17,27,44,.98),rgba(11,18,32,.98));border:1px solid rgba(52,211,153,.16);box-shadow:0 12px 28px rgba(0,0,0,.24);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC'>"
			& "<div style='font-size:11px;text-transform:uppercase;letter-spacing:.11em;color:#94A3B8;font-weight:700'>Mes anterior</div>"
			& "<div style='margin-top:15px;font-size:28px;line-height:30px;font-weight:750'>" & FORMAT ( [Receita Mes Anterior], "R$ #,##0.00" ) & "</div>"
			& "<div style='margin-top:12px;font-size:12px;color:#34D399'>base comparativa de receita</div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: 6f6a49c6-f9e2-42ee-a05c-45c2807adc08

	measure 'HTML KPI Variacao Receita' =
			VAR Delta = [Variacao Receita % vs Mes Anterior]
			VAR Positivo = Delta >= 0
			VAR Cor = IF ( Positivo, "#34D399", "#F87171" )
			VAR Fundo = IF ( Positivo, "rgba(52,211,153,.14)", "rgba(248,113,113,.14)" )
			RETURN
			    "<div style='box-sizing:border-box;height:100%;padding:16px 17px;border-radius:18px;background:linear-gradient(180deg,rgba(17,27,44,.98),rgba(11,18,32,.98));border:1px solid rgba(56,189,248,.16);box-shadow:0 12px 28px rgba(0,0,0,.24);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC'>"
			    & "<div style='font-size:11px;text-transform:uppercase;letter-spacing:.11em;color:#94A3B8;font-weight:700'>Variacao receita</div>"
			    & "<div style='margin-top:15px;font-size:34px;line-height:34px;font-weight:750;color:" & Cor & "'>" & IF ( ISBLANK ( Delta ), "-", FORMAT ( Delta, "+0.0%;-0.0%;0.0%" ) ) & "</div>"
			    & "<div style='margin-top:12px;display:inline-flex;padding:5px 9px;border-radius:999px;background:" & Fundo & ";color:" & Cor & ";font-size:12px;font-weight:700'>vs mes anterior</div>"
			    & "</div>"
		displayFolder: 05 HTML
		lineageTag: 4d10522c-617e-4fdf-a7f3-57b458285b11

	measure 'HTML KPI Ticket Medio' =
			"<div style='box-sizing:border-box;height:100%;padding:16px 17px;border-radius:18px;background:linear-gradient(180deg,rgba(17,27,44,.98),rgba(11,18,32,.98));border:1px solid rgba(167,139,250,.16);box-shadow:0 12px 28px rgba(0,0,0,.24);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC'>"
			& "<div style='font-size:11px;text-transform:uppercase;letter-spacing:.11em;color:#94A3B8;font-weight:700'>Ticket medio</div>"
			& "<div style='margin-top:15px;font-size:28px;line-height:30px;font-weight:750;color:#C4B5FD'>" & FORMAT ( [Ticket Medio], "R$ #,##0.00" ) & "</div>"
			& "<div style='margin-top:12px;font-size:12px;color:#94A3B8'>valor medio por receita</div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: e5186d38-e89d-434a-ae44-99fc2a092ad9

	measure 'HTML KPI Despesa Anterior' =
			"<div style='box-sizing:border-box;height:100%;padding:16px 17px;border-radius:18px;background:linear-gradient(180deg,rgba(17,27,44,.98),rgba(11,18,32,.98));border:1px solid rgba(248,113,113,.16);box-shadow:0 12px 28px rgba(0,0,0,.24);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC'>"
			& "<div style='font-size:11px;text-transform:uppercase;letter-spacing:.11em;color:#94A3B8;font-weight:700'>Mes anterior</div>"
			& "<div style='margin-top:15px;font-size:28px;line-height:30px;font-weight:750'>" & FORMAT ( [Despesa Mes Anterior], "R$ #,##0.00" ) & "</div>"
			& "<div style='margin-top:12px;font-size:12px;color:#F87171'>base comparativa de despesa</div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: 8e8af052-229a-45b0-9198-bf9b6eb073bc

	measure 'HTML KPI Variacao Despesa' =
			VAR Delta = [Variacao Despesa % vs Mes Anterior]
			VAR Favoravel = [Variacao Despesa vs Mes Anterior] <= 0
			VAR Cor = IF ( Favoravel, "#34D399", "#F87171" )
			VAR Fundo = IF ( Favoravel, "rgba(52,211,153,.14)", "rgba(248,113,113,.14)" )
			RETURN
			    "<div style='box-sizing:border-box;height:100%;padding:16px 17px;border-radius:18px;background:linear-gradient(180deg,rgba(17,27,44,.98),rgba(11,18,32,.98));border:1px solid rgba(248,113,113,.16);box-shadow:0 12px 28px rgba(0,0,0,.24);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC'>"
			    & "<div style='font-size:11px;text-transform:uppercase;letter-spacing:.11em;color:#94A3B8;font-weight:700'>Variacao despesa</div>"
			    & "<div style='margin-top:15px;font-size:34px;line-height:34px;font-weight:750;color:" & Cor & "'>" & IF ( ISBLANK ( Delta ), "-", FORMAT ( Delta, "+0.0%;-0.0%;0.0%" ) ) & "</div>"
			    & "<div style='margin-top:12px;display:inline-flex;padding:5px 9px;border-radius:999px;background:" & Fundo & ";color:" & Cor & ";font-size:12px;font-weight:700'>menor e melhor</div>"
			    & "</div>"
		displayFolder: 05 HTML
		lineageTag: 386fe9c5-c55e-4089-aaf3-7332755acf56

	measure 'HTML KPI Valor Medio' =
			"<div style='box-sizing:border-box;height:100%;padding:16px 17px;border-radius:18px;background:linear-gradient(180deg,rgba(17,27,44,.98),rgba(11,18,32,.98));border:1px solid rgba(167,139,250,.16);box-shadow:0 12px 28px rgba(0,0,0,.24);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC'>"
			& "<div style='font-size:11px;text-transform:uppercase;letter-spacing:.11em;color:#94A3B8;font-weight:700'>Valor medio</div>"
			& "<div style='margin-top:15px;font-size:28px;line-height:30px;font-weight:750;color:#C4B5FD'>" & FORMAT ( [Valor Medio por Lancamento], "R$ #,##0.00" ) & "</div>"
			& "<div style='margin-top:12px;font-size:12px;color:#94A3B8'>media por lancamento</div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: 7993c2cf-065f-49d6-a9ce-bbfe13fbc6ef

	measure 'HTML KPI Resultado Anterior' =
			"<div style='box-sizing:border-box;height:100%;padding:16px 17px;border-radius:18px;background:linear-gradient(180deg,rgba(17,27,44,.98),rgba(11,18,32,.98));border:1px solid rgba(245,158,11,.16);box-shadow:0 12px 28px rgba(0,0,0,.24);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC'>"
			& "<div style='font-size:11px;text-transform:uppercase;letter-spacing:.11em;color:#94A3B8;font-weight:700'>Mes anterior</div>"
			& "<div style='margin-top:15px;font-size:28px;line-height:30px;font-weight:750'>" & FORMAT ( [Resultado Mes Anterior], "R$ #,##0.00" ) & "</div>"
			& "<div style='margin-top:12px;font-size:12px;color:#F59E0B'>base comparativa do resultado</div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: 4fc34932-30fd-4d46-8976-316e20c63eec

	measure 'HTML KPI Variacao Resultado' =
			VAR Delta = [Variacao Resultado % vs Mes Anterior]
			VAR Positivo = [Variacao Resultado vs Mes Anterior] >= 0
			VAR Cor = IF ( Positivo, "#34D399", "#F87171" )
			VAR Fundo = IF ( Positivo, "rgba(52,211,153,.14)", "rgba(248,113,113,.14)" )
			RETURN
			    "<div style='box-sizing:border-box;height:100%;padding:16px 17px;border-radius:18px;background:linear-gradient(180deg,rgba(17,27,44,.98),rgba(11,18,32,.98));border:1px solid rgba(245,158,11,.16);box-shadow:0 12px 28px rgba(0,0,0,.24);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC'>"
			    & "<div style='font-size:11px;text-transform:uppercase;letter-spacing:.11em;color:#94A3B8;font-weight:700'>Variacao resultado</div>"
			    & "<div style='margin-top:15px;font-size:34px;line-height:34px;font-weight:750;color:" & Cor & "'>" & IF ( ISBLANK ( Delta ), "-", FORMAT ( Delta, "+0.0%;-0.0%;0.0%" ) ) & "</div>"
			    & "<div style='margin-top:12px;display:inline-flex;padding:5px 9px;border-radius:999px;background:" & Fundo & ";color:" & Cor & ";font-size:12px;font-weight:700'>vs mes anterior</div>"
			    & "</div>"
		displayFolder: 05 HTML
		lineageTag: 3bb2237f-889a-4960-8c3a-c37f8866a826

	measure 'HTML 1920 Background' =
			"<div style='width:1920px;height:1080px;min-width:100%;min-height:100%;box-sizing:border-box;background:#06111F;position:relative;overflow:hidden;font-family:Segoe UI,Inter,Arial,sans-serif'>"
			& "<div style='position:absolute;left:-260px;top:-280px;width:760px;height:760px;border-radius:999px;background:radial-gradient(circle,rgba(56,189,248,.18),rgba(56,189,248,.06) 34%,rgba(6,17,31,0) 70%)'></div>"
			& "<div style='position:absolute;right:-280px;bottom:-300px;width:820px;height:820px;border-radius:999px;background:radial-gradient(circle,rgba(20,184,166,.13),rgba(56,189,248,.04) 38%,rgba(6,17,31,0) 72%)'></div>"
			& "<div style='position:absolute;inset:0;background:linear-gradient(135deg,rgba(11,22,40,.78),rgba(6,17,31,.94) 45%,rgba(5,12,24,1));'></div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: 2ae03bd4-3303-4e84-a23a-db51794b67bb

	measure 'HTML 1920 Header Visao' =
			"<div style='height:100%;box-sizing:border-box;padding:22px 28px;border-radius:20px;background:linear-gradient(135deg,#0B1628 0%,#0F1B2D 58%,#06111F 100%);border:1px solid rgba(255,255,255,.08);box-shadow:0 20px 55px rgba(0,0,0,.32);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC;display:flex;align-items:center;justify-content:space-between;overflow:hidden'>"
			& "<div><div style='font-size:12px;letter-spacing:2px;text-transform:uppercase;color:#38BDF8;font-weight:800'>FINANCE EXECUTIVE SUITE</div><div style='margin-top:8px;font-size:34px;line-height:38px;font-weight:750'>Visao Executiva</div><div style='margin-top:4px;font-size:14px;color:#94A3B8'>Analise consolidada de receitas, despesas e resultado financeiro | " & [Periodo Selecionado Texto] & "</div></div>"
			& "<div style='min-width:720px;height:44px'></div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: cf973454-270e-49d9-a33b-9fe767f39e16

	measure 'HTML 1920 Header Receitas' =
			"<div style='height:100%;box-sizing:border-box;padding:22px 28px;border-radius:20px;background:linear-gradient(135deg,#0B1628 0%,#0F1B2D 58%,#06111F 100%);border:1px solid rgba(255,255,255,.08);box-shadow:0 20px 55px rgba(0,0,0,.32);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC;display:flex;align-items:center;justify-content:space-between;overflow:hidden'>"
			& "<div><div style='font-size:12px;letter-spacing:2px;text-transform:uppercase;color:#22C55E;font-weight:800'>REVENUE INTELLIGENCE</div><div style='margin-top:8px;font-size:34px;line-height:38px;font-weight:750'>Receitas</div><div style='margin-top:4px;font-size:14px;color:#94A3B8'>Entradas, recorrencia, categorias e formas de pagamento | " & [Periodo Selecionado Texto] & "</div></div>"
			& "<div style='min-width:720px;height:44px'></div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: 052d9bb8-44df-4723-9fc4-a7271e74888b

	measure 'HTML 1920 Header Despesas' =
			"<div style='height:100%;box-sizing:border-box;padding:22px 28px;border-radius:20px;background:linear-gradient(135deg,#0B1628 0%,#0F1B2D 58%,#06111F 100%);border:1px solid rgba(255,255,255,.08);box-shadow:0 20px 55px rgba(0,0,0,.32);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC;display:flex;align-items:center;justify-content:space-between;overflow:hidden'>"
			& "<div><div style='font-size:12px;letter-spacing:2px;text-transform:uppercase;color:#EF4444;font-weight:800'>COST CONTROL</div><div style='margin-top:8px;font-size:34px;line-height:38px;font-weight:750'>Despesas</div><div style='margin-top:4px;font-size:14px;color:#94A3B8'>Gastos, concentracao e maiores impactos financeiros | " & [Periodo Selecionado Texto] & "</div></div>"
			& "<div style='min-width:720px;height:44px'></div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: b929929c-7af6-4ec5-991c-10444a7484a2

	measure 'HTML 1920 Header Resultado' =
			"<div style='height:100%;box-sizing:border-box;padding:22px 28px;border-radius:20px;background:linear-gradient(135deg,#0B1628 0%,#0F1B2D 58%,#06111F 100%);border:1px solid rgba(255,255,255,.08);box-shadow:0 20px 55px rgba(0,0,0,.32);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC;display:flex;align-items:center;justify-content:space-between;overflow:hidden'>"
			& "<div><div style='font-size:12px;letter-spacing:2px;text-transform:uppercase;color:#F59E0B;font-weight:800'>PERFORMANCE</div><div style='margin-top:8px;font-size:34px;line-height:38px;font-weight:750'>Resultado Financeiro</div><div style='margin-top:4px;font-size:14px;color:#94A3B8'>Lucro, margem, acumulado e evolucao financeira | " & [Periodo Selecionado Texto] & "</div></div>"
			& "<div style='min-width:720px;height:44px'></div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: 5d38769c-c3da-452a-befb-a2fbf09f6e0b

	measure 'HTML 1920 Header Detalhamento' =
			"<div style='height:100%;box-sizing:border-box;padding:22px 28px;border-radius:20px;background:linear-gradient(135deg,#0B1628 0%,#0F1B2D 58%,#06111F 100%);border:1px solid rgba(255,255,255,.08);box-shadow:0 20px 55px rgba(0,0,0,.32);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC;display:flex;align-items:center;justify-content:space-between;overflow:hidden'>"
			& "<div><div style='font-size:12px;letter-spacing:2px;text-transform:uppercase;color:#8B5CF6;font-weight:800'>TRANSACTION EXPLORER</div><div style='margin-top:8px;font-size:34px;line-height:38px;font-weight:750'>Detalhamento</div><div style='margin-top:4px;font-size:14px;color:#94A3B8'>Consulta granular dos lancamentos financeiros | " & [Periodo Selecionado Texto] & "</div></div>"
			& "<div style='min-width:720px;height:44px'></div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: 83203348-f94f-481a-a802-0fb39c5a45b9

	measure 'HTML 1920 Card Receita' = [HTML KPI Receita]
		displayFolder: 05 HTML
		lineageTag: 0ed593ce-0b9d-4b04-8e36-598e7f14f3b0

	measure 'HTML 1920 Card Despesa' = [HTML KPI Despesa]
		displayFolder: 05 HTML
		lineageTag: dc4780e0-10b3-402a-a287-cd9b7277f99e

	measure 'HTML 1920 Card Resultado' = [HTML KPI Resultado]
		displayFolder: 05 HTML
		lineageTag: 58fd4d69-2298-4a45-831f-f85fd6e2837a

	measure 'HTML 1920 Card Margem' = [HTML KPI Margem]
		displayFolder: 05 HTML
		lineageTag: 0692ad18-5238-4c73-870c-a39a4c48c9b2

	measure 'HTML 1920 Card Lancamentos' = [HTML KPI Lancamentos]
		displayFolder: 05 HTML
		lineageTag: 275ecb0e-e372-4106-81b7-67645bf30783

	measure 'HTML Card Receita' = [HTML 1920 Card Receita]
		displayFolder: 05 HTML
		lineageTag: a9985e51-2dcb-49a2-801d-dcb9603e69d0

	measure 'HTML Card Despesa' = [HTML 1920 Card Despesa]
		displayFolder: 05 HTML
		lineageTag: f4a39d93-d593-4a96-b7a7-d9f90180dfc3

	measure 'HTML Card Resultado' = [HTML 1920 Card Resultado]
		displayFolder: 05 HTML
		lineageTag: 94dac018-9047-48a2-bfb9-0f53fc30c117

	measure 'HTML Card Margem' = [HTML 1920 Card Margem]
		displayFolder: 05 HTML
		lineageTag: 651dd64c-b437-456b-9f24-afdd6d81b310

	measure 'HTML Card Lancamentos' = [HTML 1920 Card Lancamentos]
		displayFolder: 05 HTML
		lineageTag: e4482188-90ca-45a6-a5a4-5e83863fe20c

	measure 'HTML 1920 Filter Panel' =
			"<div style='height:100%;box-sizing:border-box;padding:26px 24px;border-radius:22px;background:linear-gradient(180deg,#0F1B2D 0%,#0B1628 100%);border:1px solid rgba(255,255,255,.08);box-shadow:0 20px 55px rgba(0,0,0,.30);font-family:Segoe UI,Inter,Arial,sans-serif;color:#F8FAFC'>"
			& "<div style='font-size:12px;letter-spacing:2px;text-transform:uppercase;color:#38BDF8;font-weight:800'>Filtros</div>"
			& "<div style='margin-top:8px;font-size:24px;line-height:28px;font-weight:750'>Refine a analise financeira</div>"
			& "<div style='margin-top:8px;font-size:13px;line-height:18px;color:#94A3B8'>Periodo, categoria, forma de pagamento e tipo.</div>"
			& "<div style='margin-top:22px;display:inline-flex;padding:10px 14px;border-radius:999px;background:rgba(56,189,248,.12);border:1px solid rgba(56,189,248,.22);color:#BAE6FD;font-size:12px;font-weight:700'>Limpar filtros</div>"
			& "</div>"
		displayFolder: 05 HTML
		lineageTag: c4be22e7-feba-4719-aeee-c11ff96149a7

	measure 'HTML 1920 Insights' = [HTML Insights Visao]
		displayFolder: 05 HTML
		lineageTag: 7f07500b-cf6e-4df2-b351-76da5f4ed8ab

	column Column
		isHidden
		formatString: 0
		lineageTag: 44edac6d-547a-4d1d-8132-67983c462618
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition medidas = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = d7d7f9dda926409db919b2723823a6d9

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

